language: go
go:
- 1.8.2
before_install:
- go get gopkg.in/check.v1
- go get github.com/zmap/zcrypto
- go get golang.org/x/text
before_script:
- mkdir -p $GOPATH/src/github.com/zmap
- ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/zmap/ || true
script:
  - go test -v ./...
notifications:
    email:
      - dkumar11@illinois.edu 
